docs/
├── figures/
│   ├── Fig2A.png
│   ├── Fig2B.png
│   └── Fig3B.pdf
|   └── Fig3B.pdf
│
├── diagrams/
│   └── datamart_flow.png
│
└── supplemental/
    ├── ERD_supplement.pdf
    └── SQL_summary.md
